Company_Data <- read.csv("C:/Users/DELL/Desktop/New folder/DATA SCIENCE/ASSIGNMENTS/COMPLETED/random forest st/Company_Data (2).csv")
View(Company_Data)
library(caret)
library(randomForest)
library(tseries)
library(ggplot2)
library(plyr)
set.seed(7)
attach(Company_Data)
summary(Company_Data)
hist(CompPrice)
hist(Income)
jarque.bera.test(Income)
hist(Advertising)
hist(Population)
hist(Price)
hist(Age)
count(Company_Data$Urban)
ggplot(Company_Data)+geom_bar(aes(x=Urban))
ggplot(Company_Data)+geom_bar(aes(x=US))
hist(Sales)
cor(Company_Data)
boxplot(Sales)
pairs(Company_Data)
jarque.bera.test(Sales)
yes_no_sales<-ifelse(Sales<8.5,"No","Yes")

sales_data<-data.frame(Company_Data,yes_no_sales)
count(yes_no_sales)
ggplot(sales_data)+geom_bar(aes(x=yes_no_sales))
View(sales_data)
table(sales_data$yes_no_sales)
itraininglevels<-sample(2,nrow(sales_data),replace=TRUE,prob=c(0.70,0.03))
train_data<-sales_data[itraininglevels==1,]
test_data<-sales_data[itraininglevels==2,]                        
random_forest<-randomForest(yes_no_sales~.,data=train_data)
summary(random_forest)
random_forest
pred_randrom<-predict(random_forest,train_data)
head(pred_randrom)
confusion<-table(pred_randrom,train_data$yes_no_sales)
confusion
plot(random_forest)
accuracy<-sum(diag(confusion))/sum(confusion)
accuracy


