install.packages("caret",dependencies =TRUE)
install.packages("randomforest")
library(caret)
library(randomForest)
library(ggplot2)
data("iris")
View(iris)
attach(iris)
hist(Sepal.Length)
jarque.bera.test(Sepal.Length)
hist(Sepal.Width)
jarque.bera.test(Sepal.Width)
hist(Petal.Length)
jarque.bera.test(Petal.Length)
hist(Petal.Width)
jarque.bera.test(Petal.Width)
plot(Species)
count(Species)
setosa<-iris[iris$Species=="setosa",] 
versicolor <- iris[Species=="versicolor",]
virginica <- iris[Species=="virginica",]
train_iris <- rbind(setosa[1:25,],versicolor[1:25,],virginica[1:25,])
test_iris <- rbind(setosa[26:50,],versicolor[26:50,],virginica[26:50,])
rf_model<-randomForest(Species~.,data=iris,ntree=50)
print(rf_model)
print(importance(rf_model))
rf_pred<-predict(rf_model,iris[-5])
pred_train<-predict(rf_model,train_iris)
table(rf_pred,Species)
accuracy<-mean(train_iris$Species==predict(rf_model,train_iris))
accuracy
plot(rf_model,lwd=2)
