Stacked_Data <- stack(LabTAT)
View(Stacked_Data)
attach(Stacked_Data)
shapiro.test(LabTAT$'Lab.A')
shapiro.test(LabTAT$`Lab.B`)
shapiro.test(LabTAT$`Lab.C`)
shapiro.test(LabTAT$`Lab.D`)
summary(LabTAT)
library(car)
leveneTest(values~ ind, data = Stacked_Data)
Anova_results <- aov(values~ind,data = Stacked_Data)
summary(Anova_results)
