Computer_Data<- read.csv("C:/Users/DELL/Desktop/DATA SCIENCE/ASSIGNMENTS/multi linear reg/Computer_Data (1).csv")
View(Computer_Data)
library(dplyr)
computerdata<-select(Computer_Data,-1)
View(computerdata)
summary(computerdata)
attach(computerdata)
hist(price)
boxplot(price)
boxplot(computerdata)
cor(computerdata)
model1<-lm(price~.,data=computerdata)
summary(model1)
install.packages("car")
library(car)
vif(model1)
influenceIndexPlot(model1,id.n=3)
model2<-lm(price~speed+hd+ram+screen+cd+multi+premium+ads+trend,data=computerdata[-1441])
summary(model1)
avPlots(model1,id.n=2,id.cex=0.7)
plot(model1)
mean(model1$residuals)
sqrt(mean(model1$residuals^2))
predprice<-predict(model1,data=computerdata)
View(predprice)
plot(price,predprice)
cor(price,predprice)

log_computer<-log(computerdata)
model_log<-lm(log(price)~log(speed)+log(hd)+log(ram)+log(screen)+cd+multi+premium+log(ads)+log(trend),data=computerdata)
summary(model_log) 
mean(model_log$residuals)
sqrt(mean(model_log$residuals^2))
predprice2<-predict(model_log,data=computerdata)
View(predprice2)
plot(price,predprice2)
cor(price,predprice2)


model_sqrt<-lm(sqrt(price)~sqrt(speed)+sqrt(hd)+sqrt(ram)+sqrt(screen)+cd+multi+premium+sqrt(ads)+sqrt(trend),data=computerdata)
summary(model_sqrt)
plot(model_sqrt)
mean(model_sqrt$residuals)
sqrt(mean(model_sqrt$residuals^2))
predpricesqrt<-predict(model_sqrt,data=computerdata)
View(predpricesqrt)
summary(predpricesqrt)
cor(price,predpricesqrt)
