bookrating<- read.csv("C:/Users/DELL/Desktop/DATA SCIENCE/ASSIGNMENTS/recommendation system/book (2).csv")
View(bookrating)
install.packages("recommenderlab",dependencies =TRUE )
library(recommenderlab)
install.packages("Matrix")
library(Matrix)
library(caTools)
str(bookrating)
hist(bookrating$Book.Rating)
bookrating_matrix<-as(bookrating,'realRatingMatrix')
bookrecommendation1<-Recommender(bookrating_matrix,method="POPULAR")
predict_recommended<-predict(bookrecommendation,bookrating_matrix[10000],n=5)
listpred1<-as(predict_recommended,"list")
bookrecommendation2<-Recommender(bookrating_matrix,method="UBCF")
predict_recommended2<-predict(bookrecommendation,bookrating_matrix[10000],n=5)
listpred2<-as(predict_recommended2,"list")
books<-data.frame(listpred2)
