library(caret)
library(dplyr)
library(kernlab)
library(e1071)
library(plyr)
library(ggplot2)
salary_train<- read.csv("C:/Users/DELL/Desktop/New folder/DATA SCIENCE/ASSIGNMENTS/COMPLETED/Support vector machines st/SalaryData_Train(1).csv")
attach(salary_train)
salary_test<-read.csv("C:/Users/DELL/Desktop/New folder/DATA SCIENCE/ASSIGNMENTS/COMPLETED/Support vector machines st/SalaryData_Test(1).csv")
View(salary_train)
View(salary_test)
??kernel
?ggplot
hist(age)
count(workclass)
ggplot(salary_train)+geom_bar(aes(x=workclass))
count(education)
ggplot(salary_train)+geom_bar(aes(x=education))
count(maritalstatus)
ggplot(salary_train)+geom_bar(aes(x=maritalstatus))
count(occupation)
ggplot(salary_train)+geom_bar(aes(x=occupation))
count(relationship)
ggplot(salary_train)+geom_bar(aes(x=relationship))
count(race)
ggplot(salary_train)+geom_bar(aes(x=race))
count(sex)
ggplot(salary_train)+geom_bar(aes(x=sex))
count(native)
count(Salary)
ggplot(salary_train)+geom_bar(aes(x=Salary))
hist(capitalgain)
hist(capitalloss)
#kernel= vanilladot
model_svm<-ksvm(salary_train$Salary~.,salary_train,kernel="vanilladot")
summary(model_svm)
model_svm
pred_model<-predict(model_svm,salary_test)
mean(pred_model==salary_test$Salary)
table(pred_model,salary_test$Salary)
confusion<-pred_model==salary_test$Salary
table(confusion)
prop.table(table(confusion))

#kernel=rfdot
rf_model<-ksvm(salary_train$Salary~.,salary_train,kernel="rbfdot")
rf_model
pred_rf<-predict(rf_model,salary_test)
mean(pred_rf==salary_test$Salary)
table(pred_rf,salary_test$Salary)
confusion1<-pred_rf==salary_test$Salary
table(confusion1)

#kernel=polydot
poly_model<-ksvm(salary_train$Salary~.,salary_train,kernel="polydot")
poly_model
pred_poly<-predict(poly_model,salary_test)
mean(pred_poly==salary_test$Salary)
table(pred_poly,salary_test$Salary)
confusion2<-pred_poly==salary_test$Salary
table(confusion2)
plot(pred_poly)

#kernel=tanhdot
tanh_model<-ksvm(salary_train$Salary~.,salary_train,kernel="tanhdot")
tanh_model
pred_tanh<-predict(tanh_model,salary_test)
mean(pred_tanh==salary_test$Salary)
table(pred_tanh,salary_test$Salary)
confusion3<-pred_tanh==salary_test$Salary
table(confusion3)
plot(pred_tanh)
