ToyotaCorolla <- read.csv("C:/Users/DELL/Desktop/DATA SCIENCE/ASSIGNMENTS/multi linear reg/ToyotaCorolla.csv")
View(ToyotaCorolla)
attach(ToyotaCorolla)
head(ToyotaCorolla)
library(dplyr)
Toyota<-select(ToyotaCorolla, Price,Age_08_04,KM,HP,cc,Doors,Gears,Quarterly_Tax,Weight)
dim(Toyota)
summary(Toyota)
hist(Price)
boxplot(Price)
boxplot(Toyota)
cor(Toyota)
Toyota_model1<-lm(Price~.,data=Toyota)
summary(Toyota_model1)
install.packages("car")
library(car)
vif(Toyota_model1)
Toyota_model_cc<-lm(Price~cc,date=Toyota)
summary(Toyota_model_cc)
Toyota_model_doors<-lm(Price~Doors,date=Toyota)
summary(Toyota_model_doors)
model_cc_doors<-lm(Price~cc+Doors,data=Toyota)
summary(model_cc_doors)
influenceIndexPlot(Toyota_model1,data=Toyota)
Toyota_model1inf<-lm(Price~.,data=Toyota[-81])
summary(Toyota_model1inf)
#high VIF for cc than doors and drop cc
Toyota_model2<-lm(Price~Age_08_04+KM+HP+Doors+Gears+Quarterly_Tax+Weight,data=Toyota)
summary(Toyota_model2)
Toyota_modelfinal<-lm(Price~Age_08_04+KM+HP+Gears+Quarterly_Tax+Weight,data=Toyota)
summary(Toyota_modelfinal)
plot(Toyota_modelfinal)
mean(Toyota_modelfinal$residuals)
sqrt(mean(Toyota_modelfinal$residuals^2))
predictprice<-predict(Toyota_modelfinal,data=Toyota)
View(predictprice)
plot(Price,predictprice)
cor(Price,predictprice)

Toyota_model_log<-lm(log(Price)~log(Age_08_04)+log(KM)+log(HP)+log(Gears)+log(Quarterly_Tax)+log(Weight),data=Toyota)
mean(Toyota_model_log$residuals)
sqrt(mean(Toyota_model_log$residuals^2))
predictprice_log<-predict(Toyota_model_log,data=Toyota)
cor(Price,predictprice_log)

Toyota_model_sqrt<-lm(sqrt(Price)~sqrt(Age_08_04)+sqrt(KM)+sqrt(HP)+sqrt(Gears)+sqrt(Quarterly_Tax)+sqrt(Weight),data=Toyota)
summary(Toyota_model_sqrt)
mean(Toyota_model_sqrt$residuals)
sqrt(mean(Toyota_model_sqrt$residuals^2))
predictprice_sqrt<-predict(Toyota_model_sqrt,data=Toyota)
cor(Price,predictprice_sqrt)
